cookie:
  cookie_expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      first_name: John
      last_name: Smith
      logged_in: false
      name: John Smith
      password: $2b$12$nHSly0dPN9qca5utmWmrR.n1RXxDGiXp02.fSbbTXCS6p7qFZM8wC
    rbriggs:
      email: rbriggs@gmail.com
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$a2FAxKKU1cLaGmpqvyz5EOjwnCAouyZcDg2nELRfXxqir1BhBXVo6
